"""encrypt tokens, drop refresh_token unique constraint

Revision ID: 45e1fea54d92
Revises: d979c649a852
Create Date: 2026-08-31 20:00:41.601418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e1fea54d92'
down_revision: Union[str, Sequence[str], None] = 'd979c649a852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Bestehende Tokens sind im Klartext gespeichert und ab hier als Fernet-Chiffrat
    # gelesen -> vor dem Constraint-Drop leeren, sonst crasht das nächste SELECT beim
    # Entschlüsseln. Betroffene Nutzer werden beim nächsten Login automatisch neu befüllt.
    op.execute("UPDATE users SET access_token = NULL, refresh_token = NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_refresh_token_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_refresh_token_key'), 'users', ['refresh_token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
